# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
product_key: chef-server

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-server-notify

automate:
  organization: products
  project: chef-server

github:
  delete_branch_on_merge: true
  # The file where the MAJOR.MINOR.PATCH version is kept. The version in this file
  # is bumped automatically via the `built_in:bump_version` merge_action.
  version_file: "VERSION"
  # The file where our CHANGELOG is kept. This file is updated automatically with
  # details from the Pull Request via the `built_in:update_changelog` merge_action.
  changelog_file: "CHANGELOG.md"

# Habitat + Docker exporting
habitat_packages:
  - openresty-noroot:
      source: src/openresty-noroot
      bldr_paths: src/openresty-noroot/*
  - oc-id:
      source: src/oc-id
      bldr_paths: src/oc-id/*
      export:
        - docker
  - chef-server-nginx:
      source: src/nginx
      bldr_paths: src/nginx/*
      export:
        - docker
  - bookshelf:
      source: src/bookshelf
      bldr_paths: src/bookshelf/*
      export:
        - docker
  - chef-server-ctl:
      source: src/chef-server-ctl
      bldr_paths: src/chef-server-ctl/*
      export:
        - docker
  - oc_bifrost:
      source: src/oc_bifrost
      bldr_paths: src/oc_bifrost/*
      export:
        - docker
  - oc_erchef:
      source: src/oc_erchef
      bldr_paths: src/oc_erchef/*
      export:
        - docker

# These actions are taken, in order they are specified, anytime a Pull Request is merged.
merge_actions:
  - built_in:bump_version:
      post_commit: false
      ignore_labels:
        - "Version: Skip Bump"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
  - built_in:update_changelog:
      post_commit: false
      ignore_labels:
        - "Changelog: Skip Update"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
  - built_in:trigger_omnibus_build:
      post_commit: true
      ignore_labels:
        - "Omnibus: Skip Build"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
      only_if: built_in:bump_version
  - built_in:trigger_habitat_package_build:
      post_commit: true
      ignore_labels:
        - "Omnibus: Skip Build"
        - "Expeditor: Skip All"
        - "Expeditor: ACC Only"
      only_if: built_in:bump_version
  - bash:.expeditor/upload-files.sh:
      post_commit: true
      only_if: built_in:trigger_habitat_package_build
      ignore_labels:
        - "Expeditor: Skip All"
  - bash:.expeditor/purge-cdn.sh:
      post_commit: true
      ignore_labels:
        - "Expeditor: Skip All"
  - built_in:update_acc:
      post_commit: true
      only_if_labels:
        - "Expeditor: ACC Only"

# Subscription to workload action of pull request merge to master branch on
# omnibus-software project will allow us to trigger an uncached omnibus build
# for chef-server when the omnibus-software has modified software config files.
subscriptions:
  # chef/omnibus-software
  - workload: pull_request_merged:chef/omnibus-software:master:*
    actions:
      - built_in:trigger_omnibus_expcache_build:
          only_if_modified:
            - config/software/*
  # TODO: add action to update changelog with modified omnibus components
  - workload: artifact_published:unstable:chef-server:*
    actions:
      - built_in:update_acc
  - workload: artifact_published:current:chef-server:*
  - workload: artifact_published:stable:chef-server:*
    actions:
      - built_in:rollover_changelog
      - built_in:notify_chefio_slack_channels

promote:
  action:
    - built_in:promote_artifactory_artifact
    - bash:.expeditor/promote_harts_and_containers.sh
    - bash:.expeditor/purge_cdn.sh
  channels:
    - acceptance
    - current
    - stable
